---
abstract: 'Call methods on objects in other processes or on other hosts'
author:
  - 'mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Object-Remote
no_index:
  directory:
    - t
    - inc
requires:
  Class::C3: 0
  Future: 0.1
  JSON::PP: 0
  Log::Contextual: 0.005
  MRO::Compat: 0
  Module::Runtime: 0
  Moo: 1.001
  String::ShellQuote: 0
version: 0.003002
